### PR TITLE
remove genericons

### PR DESCRIPTION
**Pull request by mikeyrayvon**
ive never used genericons on a project. i dont think it needs to be included by default in the boiler. maybe put it in the sync instead??

### CODE REVIEW

**Comment by varffs** [comment]
There are the 2 other icon fonts in the boiler now as well. I kinda agree they are a bit bloaty. I wonder if we could keep everything tho and have some kind of script than cleans out that we can use as part of the go live checklist? Maybe would have to be bash? @mixcas ?

**Comment by mikeyrayvon** [comment]
but ive never used genericons on a project

**Comment by mikeyrayvon** [comment]
as i understand it the boilerplate contains things we expect to use at least most of the time

**Comment by mixcas** [comment]
i think we should remove them. most of the time we end up using svgs

**Comment by varffs** [comment]
Yes the question is more about the nature of what goes in a boiler really. My feeling is that the boiler is things we use all the time (grid, basic styles, CMB2), but also could include a tool box of stuff that can be useful like icon fonts or (I want to add this but haven't got round to it) moment-php things like that

**Comment by mikeyrayvon** [comment]
yea but if i had a really weird screwdriver, like 15 sided bit or something, and i never used it and i needed room in my toolbox, or like my toolbox was already kinda heavy, id probably leave that shit at home in my drawer

**Comment by mikeyrayvon** [comment]
also i said i didnt like this like as soon as we started the using this boil, but i let it go cause i thought ok maybe hes got a point lets see, one year later - never touched

**Comment by mikeyrayvon** [comment]
damn now that i know yal are making branches to improve the boil im going innnnnnn

**Comment by varffs** [comment]
what you mean your going in? imo thats a bad analogy as it costs nothing, but yh iconfonts are very infrequently used. imo if genericons are going to go we should get rid of the other 2 iconfonts as well. i dont see the point in removing really but if thats consensus then fine by me

**Comment by mikeyrayvon** [comment]
its not consensus unless you agree mine guy

**Comment by mikeyrayvon** [comment]
idk whatever lets keep it for now. we can revisit this in a few months

**Pull request closed without merging**
